format_version: 3
common:
    
pipelines:
    api-dev:
        group: dev
        materials:
            git:
                git: https://github.com/ljsimin/retro-qr.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
            - deploy:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
                approval:
                    type: manual
    web-dev:
        group: dev
        materials:
            git:
                git: https://github.com/ljsimin/retro-qr.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
            - deploy:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
                approval:
                    type: manual
    api-stage:
        group: stage
        materials:
            git:
                git: https://github.com/ljsimin/retro-qr.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
            - deploy:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
                approval:
                    type: manual
    web-stage:
        group: stage
        materials:
            git:
                git: https://github.com/ljsimin/retro-qr.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
            - deploy:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: sleep
                                arguments:
                                    - 10
                            - exec:
                                command: ls
                approval:
                    type: manual