pipelines:
    api:
        group: dev
        materials:
            git:
                git: https://github.com/ljsimin/retro-qr.git
        stages:
            - build:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: ls
            - deploy:
                jobs:
                    build:
                        tasks:
                            - exec:
                                command: ls